CloudTerminal/Controllers/HomeController.cs
using CloudSense.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace CloudSense.Controllers
{
    public class HomeController : Controller
    {
        private DataAccess db = new DataAccess();

        public ActionResult Index()
        {
            HomeIndexViewModel model = null;

            if (ClaimsPrincipal.Current.Identity.IsAuthenticated)
            {
                model = new HomeIndexViewModel();
                model.UserOrganizations = new Dictionary<string, Organization>();
                model.UserSubscriptions = new Dictionary<string, Subscription>();
                model.UserCanManageAccessForSubscriptions = new List<string>();
                model.DisconnectedUserOrganizations = new List<string>();

                var orgnaizations = AzureResourceManagerUtil.GetUserOrganizations();
                foreach (Organization org in orgnaizations)
                {
                    model.UserOrganizations.Add(org.Id, org);
                    var subscriptions = AzureResourceManagerUtil.GetUserSubscriptions(org.Id);

                    if (subscriptions != null)
                    {
                        foreach (var subscription in subscriptions)
                        {

                            Subscription s = db.Subscriptions.Find(subscription.Id);
                            if (s != null)
                            {
                                subscription.IsConnected = true;
                                subscription.ConnectedOn = s.ConnectedOn;
                                subscription.ConnectedBy = s.ConnectedBy;
                                subscription.AzureAccessNeedsToBeRepaired = !AzureResourceManagerUtil.ServicePrincipalHasReadAccessToSubscription(subscription.Id, org.Id);
                            }
                            else
                            {
                                subscription.IsConnected = false;
                            }

                            model.UserSubscriptions.Add(subscription.Id, subscription);
                            if (AzureResourceManagerUtil.UserCanManageAccessForSubscription(subscription.Id, org.Id))
                                model.UserCanManageAccessForSubscriptions.Add(subscription.Id);
                        }
                    }
                    else
                        model.DisconnectedUserOrganizations.Add(org.Id);
                }
            }
            return View(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Dashboard()
        {
            HomeIndexViewModel model = null;

            if (ClaimsPrincipal.Current.Identity.IsAuthenticated)
            {
                model = new HomeIndexViewModel();
                model.UserOrganizations = new Dictionary<string, Organization>();
                model.UserSubscriptions = new Dictionary<string, Subscription>();
                model.UserCanManageAccessForSubscriptions = new List<string>();
                model.DisconnectedUserOrganizations = new List<string>();

                var orgnaizations = AzureResourceManagerUtil.GetUserOrganizations();
                foreach (Organization org in orgnaizations)
                {
                    model.UserOrganizations.Add(org.Id, org);
                    var subscriptions = AzureResourceManagerUtil.GetUserSubscriptions(org.Id);

                    if (subscriptions != null)
                    {
                        foreach (var subscription in subscriptions)
                        {

                            Subscription s = db.Subscriptions.Find(subscription.Id);
                            if (s != null)
                            {
                                subscription.IsConnected = true;
                                subscription.ConnectedOn = s.ConnectedOn;
                                subscription.ConnectedBy = s.ConnectedBy;
                                subscription.AzureAccessNeedsToBeRepaired = !AzureResourceManagerUtil.ServicePrincipalHasReadAccessToSubscription(subscription.Id, org.Id);
                            }
                            else
                            {
                                subscription.IsConnected = false;
                            }

                            model.UserSubscriptions.Add(subscription.Id, subscription);
                            if (AzureResourceManagerUtil.UserCanManageAccessForSubscription(subscription.Id, org.Id))
                                model.UserCanManageAccessForSubscriptions.Add(subscription.Id);
                        }
                    }
                    else
                        model.DisconnectedUserOrganizations.Add(org.Id);
                }
            }
            return View(model);
        }

        public ActionResult VirtualMachines()
        {
            return View();
        }

        public string GetVirtualMachines(string SubId)
        {
            return AzureResourceManagerUtil.GetVirtualMachines(SubId);
        }

        public string GetVMInfo(string Id)
        {
            return AzureResourceManagerUtil.GetVMInfo(Id);
        }

        public string CallAPI(string API, string ApiType = "GET")
        {
            return AzureResourceManagerUtil.CallAPI(API, ApiType);
        }

        public ActionResult Board()
        {
            return View();
        }

        public ActionResult SqlServers()
        {
            return View();
        }

        public ActionResult Features()
        {
            return View();
        }

        public ActionResult Storage()
        {
            return View();
        }

        public ActionResult Website()
        {
            return View();
        }

        public ActionResult ServiceBus()
        {
            return View();
        }


        public ActionResult BreadCrumb()
        {
            return View();
        }

    }
}

CloudTerminal/Controllers/ServiceBusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudSense.Controllers
{
    public class ServiceBusController : Controller
    {
        // GET: ServiceBus
        public ActionResult Explorer()
        {
            return View();
        }
        public ActionResult Queues()
        {
            return View();
        }
        public ActionResult Topics()
        {
            return View();
        }
    }
}

CloudTerminal/Controllers/StorageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudSense.Controllers
{
    public class StorageController : Controller
    {
        // GET: Storage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }
    }
}

CloudTerminal/Controllers/SubscriptionController.cs
using CloudSense.Models;
using System;
using System.Collections.Generic;
using System.IdentityModel.Claims;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CloudSense.Controllers
{
    public class SubscriptionController : Controller
    {
        private DataAccess db = new DataAccess();

        public ActionResult Connect([Bind(Include = "Id, OrganizationId")] Subscription subscription, string servicePrincipalObjectId)
        {
            if (ModelState.IsValid)
            {
                AzureResourceManagerUtil.GrantRoleToServicePrincipalOnSubscription(servicePrincipalObjectId, subscription.Id, subscription.OrganizationId);
                if (AzureResourceManagerUtil.ServicePrincipalHasReadAccessToSubscription(subscription.Id, subscription.OrganizationId))
                {
                    subscription.ConnectedBy = (System.Security.Claims.ClaimsPrincipal.Current).FindFirst(ClaimTypes.Name).Value;
                    subscription.ConnectedOn = DateTime.Now;

                    db.Subscriptions.Add(subscription);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index", "Home");
        }
        public ActionResult Disconnect([Bind(Include = "Id, OrganizationId")] Subscription subscription, string servicePrincipalObjectId)
        {
            if (ModelState.IsValid)
            {
                AzureResourceManagerUtil.RevokeRoleFromServicePrincipalOnSubscription(servicePrincipalObjectId, subscription.Id, subscription.OrganizationId);

                Subscription s = db.Subscriptions.Find(subscription.Id);
                if (s != null)
                {
                    db.Subscriptions.Remove(s);
                    db.SaveChanges();
                }
                
            }

            return RedirectToAction("Index", "Home");
        }
        public ActionResult RepairAccess([Bind(Include = "Id, OrganizationId")] Subscription subscription, string servicePrincipalObjectId)
        {
            if (ModelState.IsValid)
            {
                AzureResourceManagerUtil.RevokeRoleFromServicePrincipalOnSubscription(servicePrincipalObjectId, subscription.Id, subscription.OrganizationId);
                AzureResourceManagerUtil.GrantRoleToServicePrincipalOnSubscription(servicePrincipalObjectId, subscription.Id, subscription.OrganizationId);
            }

            return RedirectToAction("Index", "Home");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CloudTerminal/Views/Home/Board.cshtml
<div ng-init="ListAllBoardResources()">

    <div class="row">
        <div id="filters" class="btn-group pull-right">
            <a href="javascript:;" ng-click="statusFilter=null" ng-class="{active: statusFilter==null} " class="btn btn-primary"><i class="fa  icon-azure-icon-microsoft-azure"></i>All</a>
            <a href="javascript:;" ng-click="statusFilter={DataService:true}" ng-class="{active: statusFilter.DataService}" class="btn btn-primary"><i class="fa  icon-azure-icon-data-services"></i>Data Service</a>
            <a href="javascript:;" ng-click="statusFilter={Compute:true}" ng-class="{active: statusFilter.Compute}" class="btn btn-primary"><i class="fa  icon-azure-icon-compute"></i>Compute</a>
            <a href="javascript:;" ng-click="statusFilter={AppServices:true}" ng-class="{active: statusFilter.AppServices}" class="btn btn-primary"><i class="fa  icon-azure-icon-app-services fa"></i>App Services</a>
        </div>
    </div>
   
    <div class="row" style="margin-top:10px">
        <div class=" col-lg-3 col-md-6 ng-isolate-scope" ng-show="statusFilter.Compute ==true || statusFilter == null">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa icon-azure-icon-virtual-machine fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge ng-binding">{{VMList.length}}</div>
                            <div class="ng-binding">Virtual Machines</div>
                        </div>
                    </div>
                </div>
                <a ui-sref="home.Dashboard.VirtualMachines">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>


            </div>

        </div>

        <div class="col-lg-3 col-md-6 ng-isolate-scope" ng-show="statusFilter.DataService ==true || statusFilter == null">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa icon-azure-icon-sql-database-generic fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge ng-binding">{{SQLServerList.length}}</div>
                            <div class="ng-binding">SQL Databases</div>
                        </div>
                    </div>
                </div>
                <a ui-sref="home.Dashboard.SQLDatabases">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>


            </div>

        </div>

        <div class="col-lg-3 col-md-6 ng-isolate-scope" ng-show="statusFilter.DataService ==true || statusFilter == null">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa icon-azure-icon-storage-azure fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge ng-binding">{{StorageList.length}}</div>
                            <div class="ng-binding">Storage</div>
                        </div>
                    </div>
                </div>
                <a ui-sref="home.Dashboard.Storage">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>


            </div>

        </div>

        <div class="col-lg-3 col-md-6 ng-isolate-scope" ng-show="statusFilter.Compute == true || statusFilter == null">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa icon-azure-icon-azure-websites fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge ng-binding">{{WebsiteList.length}}</div>
                            <div class="ng-binding">Web Apps</div>
                        </div>
                    </div>
                </div>
                <a ui-sref="home.Dashboard.WebSites">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>


            </div>

        </div>

        <div class="col-lg-3 col-md-6 ng-isolate-scope" ng-show="statusFilter.AppServices == true || statusFilter == null">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa icon-azure-icon-service-bus fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge ng-binding">{{ServiceBusList.length}}</div>
                            <div class="ng-binding">Service Bus</div>
                        </div>
                    </div>
                </div>
                <a ui-sref="home.Dashboard.ServiceBus">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>


            </div>

        </div>

    </div>
</div>

CloudTerminal/Views/Home/BreadCrumb.cshtml
<ol class="breadcrumb">
    <li ng-repeat="crumb in breadcrumbs"
        ng-class="{ active: $last }">
        <a ui-sref="{{ crumb.route }}" ng-if="!$last">{{ crumb.displayName }}&nbsp;</a><span ng-show="$last">{{ crumb.displayName }}</span>
    </li>
</ol>

CloudTerminal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CloudTerminal/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h2></h2>
<div ng-init="ListAllResources()">

    <div class="container white_bg">

        <div class="col-md-1 col-sm-4 col-xs-12">
            @*<div class="link_box">
                <h3>
                    <i class="fa fa-bullhorn"></i>
                    Stay Updated
                </h3>
            </div>*@
        </div>
        <div class="col-md-9 col-sm-8 col-xs-12">
            @if (Request.IsAuthenticated)
            {
                <div class="row">
                    <table class="table table-striped table-condensed pull-down">
                        <thead>
                            <tr>
                                <th><a ng-click="" href="javascript:;">Subscription Name</a></th>
                                <th><a ng-click="" href="javascript:;">Subscription Id</a></th>
                                <th><a ng-click="" href="javascript:;">State</a></th>
                                <th></th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="item in data" class="ng-scope">
                                <td>
                                    <a ui-sref="home.Dashboard({SubId: item.Id})" class="btn class=" btn btn-link">
                                        {{item.DisplayName}}
                                    </a>
                                </td>
                                <td class="ng-binding">{{item.Id}}</td>
                                <td class="ng-binding">{{item.state}}</td>
                                <td class="text-right"><i class="fa icon-azure-icon-azure-subscription fa-2x" title="Responsive device"></i></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            }
            @if (!Request.IsAuthenticated)
            {
                <div inform class="inform-fixed"></div>
                <h2 class="page_heading">CLOUD TERMINAL</h2>
                <div>
                    <p align="justify">
                        Cloud terminal is a web based portal that can be used to manage your azure subscription
                    </p>
                </div>
    <div class="row" style="margin-top:10px">

        <div class="col-md-6 col-sm-12 cnt_links">
            <ul class="nav nav-pills nav-stacked" id="ctl00_CenterLink_ImpLinks">
                <li class="active">
                    <a href="" target="_blank">
                        <i class="fa icon-azure-icon-virtual-machine fa-2x" title="Virtual Machines"></i>
                        Manage your Azure Virtual Machines
                    </a>
                </li>
            </ul>
        </div>
    </div>

                <div class="row" style="margin-top:10px">
                    <div class="col-md-6 col-sm-12 cnt_links">
                        <ul class="nav nav-pills nav-stacked" id="ctl00_CenterLink_ImpLinks">
                            <li class="active">
                                <a href="" target="_blank">
                                    <i class="fa icon-azure-icon-sql-database-generic fa-2x" title="sql-database"></i>
                                    Manage your Azure SQL Databases and Servers
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
    <div class="row" style="margin-top:10px">
        <div class="col-md-6 col-sm-12 cnt_links">
            <ul class="nav nav-pills nav-stacked" id="ctl00_CenterLink_ImpLinks">
                <li class="active">
                    <a href="" target="_blank">
                        <i class="fa icon-azure-icon-storage-azure fa-2x" title="storage-azure"></i>
                        Manage your Azure Storage Accounts
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row" style="margin-top:10px">
        <div class="col-md-6 col-sm-12 cnt_links">
            <ul class="nav nav-pills nav-stacked" id="ctl00_CenterLink_ImpLinks">
                <li class="active">
                    <a href="" target="_blank">
                        <i class="fa icon-azure-icon-azure-websites fa-2x" title="storage-azure"></i>
                        Manage your Azure Web Applications
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row" style="margin-top:10px">
        <div class="col-md-6 col-sm-12 cnt_links">
            <ul class="nav nav-pills nav-stacked" id="ctl00_CenterLink_ImpLinks">
                <li class="active">
                    <a href="" target="_blank">
                        <i class="fa icon-azure-icon-service-bus fa-2x" title="storage-azure"></i>
                        Manage your Azure ServiceBus Namespace
                    </a>
                </li>
            </ul>
        </div>
    </div>

            }
        </div>


    </div>


</div>

CloudTerminal/Views/Home/Index1.cshtml
@model CloudSense.Models.HomeIndexViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>CloudSense</h1>
    <p class="lead">We monitor your Azure infrastructure. You ... sleep well.</p>
</div>

<div class="row">
    @if (!Request.IsAuthenticated)
    {
        <div class="col-lg-4 thumbnail">
            <div class="caption">
                <h3>Sign-in to connect your Azure Subscription</h3>
                <div id="org"><a href='@Url.Action("SignIn", "Account")'><img src="~/Images/org.png" style="height:65px;width:350px;margin:0px" class="img-thumbnail" /></a></div>
                <span id="back" style="display:none; cursor:pointer" class="glyphicon glyphicon-arrow-left"></span>
                <div id="msa" style="cursor:pointer"><img src="~/Images/msa.png" style="height:64px;width:350px" class="img-thumbnail" /></div>

                @using (Html.BeginForm("SignIn", "Account", new { isMSA = true }, FormMethod.Get))
                {
                    <div id="msadir" style="display: none">
                        <div class="input-group" style="width:350px">
                            <input name="directoryName" type="text" class="form-control" placeholder="Directory Name e.g. contoso.com" aria-describedby="basic-addon2">
                            <input name="isMSA" type="hidden" value="true" />
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">Go</button>
                            </span>
                        </div>
                        <a style="font-size:smaller; cursor:pointer" data-toggle="modal" data-target=".bs-example-modal-lg">Help me find my directory name</a>
                    </div>
                }
            </div>
        </div>
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class=" modal-dialog modal-lg">
                <div class="modal-content">
                    <img src="~/Images/directory.png" />
                </div>
            </div>
        </div>
    }
    else if (Model != null)
    {
        <table class="table table-striped table-condensed table-hover">
            <tr>
                <td>
                    <h4>Azure Subscription</h4>
                </td>
                <td>
                    <h4>Monitored by CloudSense?</h4>
                </td>
            </tr>
            @foreach (KeyValuePair<string, CloudSense.Models.Subscription> entry in Model.UserSubscriptions)
            {
                var subscription = entry.Value as CloudSense.Models.Subscription;
                <tr>
                    <td>
                        @subscription.DisplayName
                        <br />
                        &nbsp;&nbsp;<small>Subscription Id: @subscription.Id</small>
                        <br />
                        &nbsp;&nbsp;<small>Organization Id: @subscription.OrganizationId</small>
                    </td>
                    <td>
                        @if (subscription.IsConnected)
                        {
                            <text>Yes. </text>
                            <br />
                            <small>&nbsp;&nbsp; Connected By: @subscription.ConnectedBy </small>
                            <small>&nbsp; Connected On: @subscription.ConnectedOn.ToShortDateString() </small>
                            if (Model.UserCanManageAccessForSubscriptions.Contains(@subscription.Id))
                            {

                                @Html.ActionLink("Disconnect", "Disconnect", "Subscription", new
                                    {
                                        Id = @subscription.Id,
                                        OrganizationId = @subscription.OrganizationId,
                                        ServicePrincipalObjectId = Model.UserOrganizations[@subscription.OrganizationId].objectIdOfCloudSenseServicePrincipal
                                    },
                                    new { @class = "btn btn-danger btn-xs" })
                            }
                            if (@subscription.AzureAccessNeedsToBeRepaired)
                            {
                                <br />
                                <small>&nbsp;&nbsp; Access in Azure needs to be repaired: </small>
                                @Html.ActionLink("Repair", "RepairAccess", "Subscription", new
                                    {
                                        Id = @subscription.Id,
                                        OrganizationId = @subscription.OrganizationId,
                                        ServicePrincipalObjectId = Model.UserOrganizations[@subscription.OrganizationId].objectIdOfCloudSenseServicePrincipal
                                    },
                                    new { @class = "btn btn-info btn-xs" })
                            }
                        }
                        else
                        {
                            <text>No. </text>
                            if (Model.UserCanManageAccessForSubscriptions.Contains(@subscription.Id))
                            {
                                @Html.ActionLink("Connect", "Connect", "Subscription", new
                                    {
                                        Id = @subscription.Id,
                                        OrganizationId = @subscription.OrganizationId,
                                        ServicePrincipalObjectId = Model.UserOrganizations[@subscription.OrganizationId].objectIdOfCloudSenseServicePrincipal
                                    },
                                    new { @class = "btn btn-success btn-xs" })
                            }
                        }
                        @if (!Model.UserCanManageAccessForSubscriptions.Contains(@subscription.Id))
                        {
                            <text>(You can't manage access for this subscription.)</text>
                        }
                    </td>
                </tr>
            }
        </table>
        if (Model.DisconnectedUserOrganizations.Count > 0)
        {
            <div class="alert alert-warning" role="alert">
                <h4> Didn't find the Azure subscription that you want to connect? </h4>
                <h5>
                    It could be in the @Model.DisconnectedUserOrganizations.Count other Organization(s) of which you're a member.
                    Click here to connect to all your Organizations (you will need to provide consent for each).
                </h5>
            </div>
        }
    }
    <div class="col-lg-3 col-md-6 ng-isolate-scope" type="comments" colour="primary">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-desktop fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge ng-binding">{{VMList.length}}</div>
                        <div class="ng-binding">Virtual Machines</div>
                    </div>
                </div>
            </div>
            <a href="#" ng-click="resources()">
                <div class="panel-footer">
                    <span id="id4" class="pull-left">View Details</span>
                    <span class="pull-right">
                        <i class="fa fa-arrow-circle-right"></i>
                    </span>
                    <div class="clearfix"></div>
                </div>
            </a>

            {{people}}

        </div>

    </div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(
     function () {
         $("#msa").click(function () {
             $("#org").hide();
             $("#back").show();
             $("#msadir").show("slow");
         });
         $("#back").click(function () {
             $("#back").hide();
             $("#msadir").hide();
             $("#org").show("slow");
         });


        
     });
</script>